bookmark/urls.py
from django.urls import path

from bookmark.views import bookmark_detail, bookmark_create, bookmark_update, bookmark_delete, bookmark_list, bookmark_archive

app_name = 'bookmark'

urlpatterns = [
	path('create/', bookmark_create, name="create"),
	path('<id>/', bookmark_detail, name="detail"),
	path('<id>/update/', bookmark_update, name="update"),
	path('<id>/delete/', bookmark_delete, name="delete"),
	path('<id>/check/', bookmark_archive, name="check"),

]

crashcourse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static
from crashcourse.views import list_all, get_db_as_json
from django.contrib.auth.views import LoginView, LogoutView
from .views import  SignupView
urlpatterns = [
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('signup/', SignupView.as_view(), name='signup'),

	path('admin/', admin.site.urls),

	path('', list_all),
	path('todo/', include('todo.urls', namespace="todo")),
	path('note/', include('note.urls', namespace="note")),
	path('bookmark/', include('bookmark.urls', namespace="bookmark")),
	path('getdb/', get_db_as_json, name="export-user-db"),

]
if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path

from .views import note_detail, note_create, note_update, note_delete, note_archive

app_name = 'note'

urlpatterns = [
	path('create/', note_create, name="create"),
	path('<id>/', note_detail, name="detail"),
	path('<id>/update/', note_update, name="update"),
	path('<id>/delete/', note_delete, name="delete"),
	path('<id>/check/', note_archive, name="check"),
]

bookmark/models.py
from django.db import models
from django.utils import timezone

from tags.models import Tag


class Bookmark(models.Model):
	name = models.CharField(max_length=90)
	tags = models.ManyToManyField(Tag, related_name='bookmark_tags')
	description = models.CharField(max_length=500)
	url = models.URLField()
	item_type = models.CharField(default="Bookmark", max_length=16, null=False)
	date_created = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.name

bookmark/forms.py
from django import forms

from .models import Bookmark


class BookmarkForm(forms.ModelForm):
	class Meta:
		model = Bookmark
		fields = ['name', 'description', 'url']
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control mb-2 w-100'}),
			'description': forms.Textarea(attrs={'class': 'form-control mb-2 w-100'}),
			# 'tags': forms.CharField(attrs={'class': 'form-control mb-2 w-100'}),
			'url': forms.TextInput(attrs={'class': 'form-control mb-2', 'type': 'url'}),
		}

bookmark/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from .forms import BookmarkForm
from .models import Bookmark


def bookmark_list(request):
	bookmarks = Bookmark.objects.all()
	paginator = Paginator(bookmarks, 12)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	context = {
		"page_obj": page_obj,

	}
	return render(request, "bookmark/bookmark_list.html", context)


def bookmark_detail(request, id):
	bookmark = Bookmark.objects.get(id=id)
	context = {
		"bookmark": bookmark,
	}
	return render(request, "bookmark/bookmark_detail.html", context)


def bookmark_create(request):
	form = BookmarkForm(request.POST or None)
	context = {
		"form": form,
	}
	if form.is_valid():
		form.save()
		return redirect('/bookmark/')
	return render(request, "bookmark/bookmark_create.html", context)


def bookmark_update(request, id):
	bookmark = Bookmark.objects.get(id=id)
	form = BookmarkForm(request.POST or None, instance=bookmark)
	if form.is_valid():
		form.save()
		return redirect('/bookmark/')
	context = {
		"form": form,
	}
	return render(request, "bookmark/bookmark_update.html", context)


def bookmark_delete(request, id):
	bookmark = Bookmark.objects.get(id=id)
	bookmark.delete()
	return redirect('/bookmark/')


def bookmark_archive(request, id):
	bookmark = Bookmark.objects.get(id=id)
	if (bookmark.checked):
		bookmark.checked = False
		bookmark.save()
	else:
		bookmark.checked = True
		bookmark.save()
	return redirect('/bookmark/')

bookmark/templates/bookmark/bookmark_create.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Create Bookmark" %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row mb-2">
                        <label for="name" style="width: 8rem;">Name</label>
                        <input class="form-control" type="text" name="name" id="name" value="">
                    </div>
                    <div class="form-row mb-2">
                        <label for="description" style="width: 8rem;">Description</label>
                        <input class="form-control" type="text" name="description" id="description" value="">
                    </div>
                    <div class="form-row mb-2">
                        <label for="url" style="width: 8rem;">URL</label>
                        <input class="form-control" type="text" name="url" id="url" value="">
                    </div>
                    <div class="form-row mt-4 d-flex justify-content-around">
                        {% include 'components/form_confirm_or_go_back.html' %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Bookmark Detail" %}
            <div class="d-flex justify-content-center">
            <div class="text-center bg-dark py-5 border border-secondary w-75 mb-3">
                <div class="">
                    <p class="lead my-1">{{ bookmark.name }}</p>
                </div>
                <div class="">
                    <p>{{ bookmark.description }}</p>
                    <a href="{{ bookmark.url }}">{{ bookmark.name }}</a>
                </div>
                <div class="mt-4 ">
                    <a class="btn btn-sm btn-warning mx-1" href="{% url 'bookmark:update' bookmark.id %}">Update</a>
                    <a class="btn btn-sm btn-danger mx-1" href="{% url 'bookmark:delete' bookmark.id %}">Delete</a>
                </div>
            </div>
                </div>
            <div class="form-row mt-4 d-flex justify-content-around">
                <button class="btn btn-danger w-25" onclick="window.history.back();" style="">Go Back</button>
            </div>
        </div>
    </div>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Update Bookmark" %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row mb-2">
                        <label for="id_name">
                            Name
                        </label>
                        {{ form.name }}
                    </div>
                    <div class="form-row mb-2">
                        <label for="id_url">
                            URL
                        </label>
                        {{ form.url }}
                    </div>
                    <div class="form-row mb-2">
                        <label for="id_description">
                            Description
                        </label>
                        {{ form.description }}
                    </div>
                    <div class="form-row mt-4 d-flex justify-content-around">
                        {% include 'components/form_confirm_or_go_back.html' %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

bookmark/templates/bookmark/list_card.html
{% load get_class %}
{% load humanize %}
<div class="card border-top-0 border-right-0 border-left-0 border-2 border-info text-center mb-3 mx-2" style="min-width: 18rem; max-width: 18rem;">
    <div class="card-header">
        <div class="card-title my-1 text-truncate">
            <a href="{{ item.url }}">{{ item }}</a>
        </div>
        <div class="small text-muted">{{ item | get_class }} <i class="bi bi-bookmark-check-fill"></i></div>
    </div>
    <div class="d-flex card-body border-left border-right border-secondary flex-column align-content-between">

        <p>{{ item.description }}</p>
    </div>
    <div class="d-flex flex-column card-footer justify-content-center py-0">
        <div class="d-flex justify-content-center pt-2">
            <form method="post" action={% url 'bookmark:check' item.id %}>
                {% csrf_token %}
                <input name="{{ bookmark.checked }}" id="{{ bookmark.checked }}" onchange="this.form.submit()" type="checkbox" class="btn-check" autocomplete="off">
                <label class="m-0 btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-primary{% endif %} mx-1" for="{{ bookmark.checked }}">Archive</label>
            </form>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-info{% endif %} mx-1" href="{% url 'bookmark:detail' item.id %}">Show</a>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-warning{% endif %} mx-1" href="{% url 'bookmark:update' item.id %}">Update</a>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-danger{% endif %} mx-1"
               onclick="if (this.innerHTML==='Confirm'){this.href='{% url 'bookmark:delete' item.id %}'};this.innerHTML='Confirm';"
               href="#">Delete</a>
        </div>
        <div class="pb-1">
            <span class="small text-muted">{{ item.date_created |naturalday }}</span>
        </div>
    </div>
</div>