crashcourse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static
from crashcourse.views import list_all, get_db_as_json
from django.contrib.auth.views import LoginView, LogoutView
from .views import  SignupView
urlpatterns = [
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('signup/', SignupView.as_view(), name='signup'),

	path('admin/', admin.site.urls),

	path('', list_all),
	path('todo/', include('todo.urls', namespace="todo")),
	path('note/', include('note.urls', namespace="note")),
	path('bookmark/', include('bookmark.urls', namespace="bookmark")),
	path('getdb/', get_db_as_json, name="export-user-db"),

]
if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path

from .views import note_detail, note_create, note_update, note_delete, note_archive

app_name = 'note'

urlpatterns = [
	path('create/', note_create, name="create"),
	path('<id>/', note_detail, name="detail"),
	path('<id>/update/', note_update, name="update"),
	path('<id>/delete/', note_delete, name="delete"),
	path('<id>/check/', note_archive, name="check"),
]

todo/urls.py
from django.urls import path

from todo.views import todo_detail, todo_create, todo_update, todo_delete, todo_check

app_name = 'todo'

urlpatterns = [
	path('create/', todo_create, name="create"),
	path('<id>/', todo_detail, name="detail"),
	path('<id>/update/', todo_update, name="update"),
	path('<id>/delete/', todo_delete, name="delete"),
	path('<id>/check/', todo_check, name="check"),
]

todo/models.py
from django.db import models
from django.utils import timezone

from tags.models import Tag


class Todo(models.Model):
	name = models.CharField(max_length=90)
	tags = models.ManyToManyField(Tag, related_name='todo_tags')
	description = models.CharField(max_length=500)
	due_date = models.DateField()
	checked = models.BooleanField(default=False)
	item_type = models.CharField(default="Todo", max_length=16, null=False)
	date_created = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.name

todo/forms.py
from django import forms

from .models import Todo


class TodoForm(forms.ModelForm):
	class Meta:
		model = Todo
		fields = ['name', 'description', 'checked', 'due_date']
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control mb-2 w-100'}),
			'description': forms.Textarea(attrs={'class': 'form-control mb-2 w-100'}),
			'checked': forms.CheckboxInput(attrs={'class': 'form-control mb-2 w-100'}),
			'due_date': forms.TextInput(attrs={'class': 'form-control mb-2', 'type': 'date'}),
		}

todo/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from .forms import TodoForm
from .models import Todo


def todo_list(request):
	todos = Todo.objects.all().order_by('due_date')
	paginator = Paginator(todos, 4)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	context = {
		"page_obj": page_obj,

	}
	return render(request, "todo/todo_list.html", context)


def todo_detail(request, id):
	todo = Todo.objects.get(id=id)
	context = {
		"todo": todo,
	}
	return render(request, "todo/todo_detail.html", context)


def todo_create(request):
	form = TodoForm(request.POST or None)
	context = {
		"form": form,
	}
	if form.is_valid():
		form.save()
		return redirect('/todo/')
	return render(request, "todo/todo_create.html", context)


def todo_update(request, id):
	todo = Todo.objects.get(id=id)
	form = TodoForm(request.POST or None, instance=todo)
	if form.is_valid():
		form.save()
		return redirect('/')
	context = {
		"form": form,
	}
	return render(request, "todo/todo_update.html", context)


def todo_check(request, id):
	todo = Todo.objects.get(id=id)
	if (todo.checked):
		todo.checked = False
		todo.save()
	else:
		todo.checked = True
		todo.save()
	return redirect('/todo/')


def todo_delete(request, id):
	todo = Todo.objects.get(id=id)
	todo.delete()
	return redirect('/todo/')

todo/templates/todo/list_card.html
{% load get_class %}
{% load humanize %}
<div class="card border-top-0 border-right-0 border-left-0 border-2 border-success text-center mb-3 mx-2" style="min-width: 18rem; max-width: 18rem;">
    <div class="card-header">
        <div class="card-title my-1 text-truncate">
            {{ item }}
        </div>
        <div class="card-subtitle small text-muted">
            <time>{{ item.due_date }}</time>
            <i class="bi bi-bell-fill"></i>
        </div>
    </div>
    <div class="d-flex card-body border-left border-right border-secondary flex-column align-content-between">
        <p>{{ item.description }}</p>
    </div>
    <div class="d-flex flex-column card-footer justify-content-center py-0">
        <div class="d-inline-flex pt-2">
            <form method="post" action={% url 'todo:check' item.id %}>
                {% csrf_token %}
                <input name="{{ todo.checked }}" id="{{ todo.checked }}" onchange="this.form.submit()" type="checkbox" class="btn-check" autocomplete="off">
                <label class="m-0 btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-primary{% endif %} mx-1" for="{{ todo.checked }}">Done</label>
            </form>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-info{% endif %} mx-1" href="{% url 'todo:detail' item.id %}">Show</a>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-warning{% endif %} mx-1" href="{% url 'todo:update' item.id %}">Update</a>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-danger{% endif %} mx-1"
               onclick="if (this.innerHTML==='Confirm'){this.href='{% url 'todo:delete' item.id %}'};this.innerHTML='Confirm';"
               href="#">Delete</a>
        </div>
        <div class="pb-1">
            <span class="small text-muted">{{ item.date_created |naturalday }}</span>
        </div>
    </div>
</div>

todo/templates/todo/todo_create.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Create Todo" %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row mb-2">
                        <label for="name" style="width: 8rem;">Name</label>
                        <input class="form-control" type="text" name="name" id="name" value="">
                    </div>
                    <div class="form-row mb-2">
                        <label for="due_date" style="width: 8rem;">Due Date</label>
                        <input class="form-control" type="date" name="due_date" id="due_date" value="">
                    </div>
                    <div class="form-row mb-2">
                        <label for="description" style="width: 8rem;">Description</label>
                        <input class="form-control" type="text" name="description" id="description" value="">
                    </div>
                    <div class="form-row mt-4 d-flex justify-content-around">
                        {% include 'components/form_confirm_or_go_back.html' %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

todo/templates/todo/todo_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Todo Details" %}
            <div class="d-flex justify-content-center">
            <div class="text-center bg-dark py-5 border border-secondary w-75 mb-3">
                  <div class="">
                    <p class="lead my-1">{{ todo }}</p>
                      <hr class="mx-5">
                </div>
                <div class="">
                    Due date: <time class="text-danger">{{ todo.due_date }}</time>
                    <p class="mt-4 text-info">{{ todo.description }}</p>
                </div>
                <div class="mt-4">
                    <a class="btn btn-sm btn-warning mx-1" href="{% url 'todo:update' todo.id %}">Update</a>
                    <a class="btn btn-sm btn-danger mx-1" href="{% url 'todo:delete' todo.id %}">Delete</a>
                </div>
            </div>
                </div>
            <div class="form-row mt-4 d-flex justify-content-around">
                <button class="btn btn-danger w-25" onclick="window.history.back();" style="">Go Back</button>
            </div>
        </div>
    </div>
{% endblock %}

todo/templates/todo/todo_update.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Update Todo" %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row mb-2">
                        <label for="id_name">
                            Name
                        </label>
                        {{ form.name }}
                    </div>
                    <div class="form-row mb-2">
                        <label for="id_due_date">
                            Due Date
                        </label>
                        {{ form.due_date }}
                    </div>
                    <div class="form-row mb-2">
                        <label for="id_description">
                            Description
                        </label>
                        {{ form.description }}
                    </div>
                    <div class="form-row mt-4 d-flex justify-content-around">
                        {% include 'components/form_confirm_or_go_back.html' %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}