crashcourse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static
from crashcourse.views import list_all, get_db_as_json
from django.contrib.auth.views import LoginView, LogoutView
from .views import  SignupView
urlpatterns = [
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('signup/', SignupView.as_view(), name='signup'),

	path('admin/', admin.site.urls),

	path('', list_all),
	path('todo/', include('todo.urls', namespace="todo")),
	path('note/', include('note.urls', namespace="note")),
	path('bookmark/', include('bookmark.urls', namespace="bookmark")),
	path('getdb/', get_db_as_json, name="export-user-db"),

]
if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path

from .views import note_detail, note_create, note_update, note_delete, note_archive

app_name = 'note'

urlpatterns = [
	path('create/', note_create, name="create"),
	path('<id>/', note_detail, name="detail"),
	path('<id>/update/', note_update, name="update"),
	path('<id>/delete/', note_delete, name="delete"),
	path('<id>/check/', note_archive, name="check"),
]

note/models.py
from django.db import models
from django.utils import timezone

from tags.models import Tag


class ArticleImage(models.Model):
	image = models.FileField(upload_to='uploads/%Y/%m/%d/')

	def __str__(self):
		return self.image.name


class Note(models.Model):
	name = models.CharField(max_length=50, null=False)
	tags = models.ManyToManyField(Tag, related_name='note_tags')
	images = models.ForeignKey(ArticleImage, null=True, on_delete=models.CASCADE)
	description = models.CharField(max_length=120, null=True)
	text_content = models.TextField(max_length=8000, null=True)
	item_type = models.CharField(default="Note", max_length=16, null=False)
	date_created = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.name

note/forms.py
from django import forms

from .models import Note, Tag


class NoteForm(forms.ModelForm):
	class Meta:
		model = Note
		fields = ['name', 'tags', 'images', 'description', 'text_content']
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control mb-2 w-100'}),
			'tags': forms.CheckboxSelectMultiple(choices=Tag.objects.all(), attrs={'class': 'form-control mb-2 w-100'}),
			# 'images':  forms.ImageField(label = 'Select a file', help_text= 'Jpg, jpeg only', required=False),
			'description': forms.TextInput(attrs={'class': 'form-control mb-2 w-100'}),
			'text_content': forms.Textarea(attrs={'class': 'form-control mb-2 w-100'}),
		}

note/views.py
from django.shortcuts import render, redirect

from .forms import NoteForm
from .models import Note


#
# def note_list(request):
# 	notes = Note.objects.all()
# 	paginator = Paginator(notes, 12)
# 	page_number = request.GET.get('page')
# 	page_obj = paginator.get_page(page_number)
# 	context = {
# 		"page_obj": page_obj,
#
# 	}
# 	return render(request, "note/note_list.html", context)


def note_detail(request, id):
	note = Note.objects.get(id=id)
	context = {
		"note": note,
	}
	return render(request, "note/note_detail.html", context)


def note_create(request):
	form = NoteForm(request.POST or None)
	context = {
		"form": form,
	}
	if form.is_valid():
		form.save()
		return redirect('/note/')
	return render(request, "note/note_create.html", context)


def note_update(request, id):
	note = Note.objects.get(id=id)
	form = NoteForm(request.POST or None, instance=note)
	if form.is_valid():
		form.save()
		return redirect('/')
	context = {
		"form": form,
	}
	return render(request, "note/note_update.html", context)


def note_delete(request, id):
	note = Note.objects.get(id=id)
	note.delete()
	return redirect('/note/')


def note_archive(request, id):
	note = Note.objects.get(id=id)
	if (note.checked):
		note.checked = False
		note.save()
	else:
		note.checked = True
		note.save()
	return redirect('/note/')

note/templates/note/list_card.html
{% load markdownify %}
{% load get_class %}
{% load humanize %}
<div class="card border-top-0 border-right-0 border-left-0 border-2 border-warning text-center mb-3 mx-2" style="min-width: 18rem; max-width: 18rem;">
    <div class="card-header">
        <div class="card-title my-1 text-truncate">
            {{ item }}
        </div>
        <div class="small text-muted">{{ item | get_class }} <i class="bi bi-file-earmark-font-fill"></i></div>
    </div>
    <div class="d-flex card-body border-left border-right border-secondary flex-column align-content-between">
        <p>{{ item.description }}</p>
        <div>
            {% for  item in item.tags.all %}
                <a href="?tags={{ item }}" class="badge badge-primary" href="">{{ item }}</a>
            {% endfor %}
        </div>
    </div>
    <div class="d-flex flex-column card-footer justify-content-center py-0">

        <div class="d-flex justify-content-center pt-2">
            <form method="post" action={% url 'note:check' item.id %}>
                {% csrf_token %}
                <input name="{{ note.checked }}" id="{{ note.checked }}" onchange="this.form.submit()" type="checkbox" class="btn-check" autocomplete="off">
                <label class="m-0 btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-primary{% endif %} mx-1" for="{{ note.checked }}">Archive</label>
            </form>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-info{% endif %} mx-1" href="{% url 'note:detail' item.id %}">Show</a>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-warning{% endif %} mx-1" href="{% url 'note:update' item.id %}">Update</a>
            <a class="btn btn-sm {% if item.checked is True %}btn-secondary{% else %}btn-danger{% endif %} mx-1"
               onclick="if (this.innerHTML==='Confirm'){this.href='{% url 'note:delete' item.id %}'};this.innerHTML='Confirm';"
               href="#">Delete</a>
        </div>
        <div class="pb-1">
            <span class="small text-muted">{{ item.date_created |naturalday }}</span>
        </div>
    </div>
</div>

note/templates/note/note_create.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Create Note" %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row mb-2">
                        <label for="name" style="width: 8rem;">Name</label>
                        <input class="form-control" type="text" name="name" id="name" value="">
                    </div>
                    <div class="form-row mb-2">
                        <label for="description" style="width: 8rem;">Card Description</label>
                        <input class="form-control" type="text" name="description" id="description" value="">
                    </div>
                    <div class="form-row mb-2">
                        {{ form.tags }}
                    </div>
                    <div class="form-row mb-2">
                        {{ form.images }}
                    </div>
                    <div class="form-row mb-2">
                        <label for="text_content" style="width: 8rem;">Description</label>
                        <textarea maxlength="8000" rows="16" class="form-control" name="text_content" id="text_content"></textarea>
                    </div>
                    <div class="form-row mt-4 d-flex justify-content-around">
                        {% include 'components/form_confirm_or_go_back.html' %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

note/templates/note/note_detail.html
{% extends "base.html" %}
{% load markdownify %}
{% block content %}
    {#    {% include 'components/page_title.html' with heading="Note Detail" %}#}
    <div class="row">
        <div class="col-10 offset-1 jumbotron border border-light mt-3">
            <div class="jumbotron">
                <h1 class="display-4">{{ note }}</h1>
                <hr>
                    {{ note.text_content |markdownify }}
            </div>
            <div class="d-flex justify-content-center mt-5">
                <a class="btn btn-sm btn-warning mx-1" href="{% url 'note:update' note.id %}">Update</a>
                <a class="btn btn-sm btn-danger mx-1" href="{% url 'note:delete' note.id %}">Delete</a>
            </div>
            <div class="form-row mt-4 d-flex justify-content-around">

                <button class="btn btn-danger w-25" onclick="window.history.back();" style="">Go Back</button>
            </div>
        </div>
    </div>
{% endblock %}

note/templates/note/note_update.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col-8 offset-2 jumbotron border border-light mt-3">
            {% include 'components/page_title.html' with heading="Update Note" %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row mb-2">
                        <label for="id_name">
                            Name
                        </label>
                        {{ form.name }}
                    </div>
                    <div class="form-row mb-2">
                        <label for="id_description">
                            Card Snippet
                        </label>
                        {{ form.description }}
                    </div>
                    <div class="form-row mb-2">
                        <label for="id_text_content">
                            Description
                        </label>
                        {{ form.text_content }}
                    </div>
                    <div class="form-row mt-4 d-flex justify-content-around">
                        {% include 'components/form_confirm_or_go_back.html' %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}