crashcourse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static
from crashcourse.views import list_all, get_db_as_json
from django.contrib.auth.views import LoginView, LogoutView
from .views import  SignupView
urlpatterns = [
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('signup/', SignupView.as_view(), name='signup'),

	path('admin/', admin.site.urls),

	path('', list_all),
	path('todo/', include('todo.urls', namespace="todo")),
	path('note/', include('note.urls', namespace="note")),
	path('bookmark/', include('bookmark.urls', namespace="bookmark")),
	path('getdb/', get_db_as_json, name="export-user-db"),

]
if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

note/urls.py
from django.urls import path

from .views import note_detail, note_create, note_update, note_delete, note_archive

app_name = 'note'

urlpatterns = [
	path('create/', note_create, name="create"),
	path('<id>/', note_detail, name="detail"),
	path('<id>/update/', note_update, name="update"),
	path('<id>/delete/', note_delete, name="delete"),
	path('<id>/check/', note_archive, name="check"),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-yJpxAFV0Ip/w63YkZfDWDTU6re/Oc3ZiVqMa97pi8uPt92y0wzeK3UFM2yQRhEom" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/pygment.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet"/>
    <title>App</title>
</head>
<body class="container mx-auto" style="margin-bottom: 5rem;">
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>

templates/footer.html
<footer class="bg-dark text-center text-white">
    <div class="container p-4">

        <section class="">
            <form action="">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-5 col-12">
                        <label class="small text-muted" for="form5Example2">
                            Let me mail you if I come up with anything cool in the future?
                        </label>
                        <div class="input-group mb-2">
                            <input type="text" class="form-control" id="" placeholder="Email 📩">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-outline-light mb-4">Subscribe</button>
                                {#                                TODO#}
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </section>
        <section class="mb-4">
            <p class="text-muted">
                I created this project to learn Django.
                {#                TODO#}
            </p>
        </section>
        <section class="">
            <div class="row">
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Reach Out</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="https://github.com/blue-hexagon" class="text-white">Github Profile</a>
                        </li>
                        <li>
                            <a href="https://news.ycombinator.com/user?id=manjana" class="text-white">Hackernews Profile</a>
                        </li>
                        <li>
                            <a href="mailto:c8u64ui5ayx5@opayq.com" class="text-white">Email</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Websites</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="https://www.cheatsheet.wtf" class="text-white">Cheatsheet.Wtf</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Misc</h5>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="#" class="text-white">Sitemap</a>
                            {#                            TODO#}
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Privacy</h5>
                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="#" class="text-white">About This Website</a>
                            {#                            TODO#}
                        </li>
                    </ul>
                </div>
            </div>
        </section>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2021 Copyright:
        <a class="text-white" href="https://github.com/blue-hexagon">@manjana</a>
    </div>
</footer>

templates/index-table.html
{% extends "base.html" %}
{% load get_class %}
{% load humanize %}
{% block content %}
    <div class="row">
        <div class="col-12 mt-2">
            <div class="jumbotron pt-4">
                {% include 'components/sorting_bar.html' %}
                <div class="d-flex flex-wrap justify-content-center mt-4">
                    <table class="table table-dark ">
{#                        <thead>#}
{#                        <tr>#}
{#                            <th style="border: none;" class="text-center">#}
{#                                Type#}
{#                            </th>#}
{#                            <th style="border: none;" class="text-left">#}
{#                                Name/Description#}
{#                            </th>#}
{#                            <th style="border: none;" class="text-center">#}
{#                                Read/Update/Archive/Delete#}
{#                            </th>#}
{#                        </tr>#}
{#                        </thead>#}
                        <tbody>
                        {% for item in page_obj %}
                            {% with itemtype=item|get_class %}
                                <tr>
                                    {# Type of Item #}
                                    <td rowspan="2" class="text-center" style="vertical-align: middle;">
                                        {% if itemtype == "Todo" %}
                                            <i class="bi bi-bell" style="font-size: 1.8rem;"></i>
                                        {% elif itemtype == "Note" %}
                                            <i class="bi bi-file-earmark" style="font-size: 1.8rem;"></i>
                                        {% elif itemtype == "Bookmark" %}
                                            <i class="bi bi-bookmark-check" style="font-size: 1.8rem;"></i>
                                        {% endif %}
                                    </td>
                                    {# Item Name + Link if relevant #}
                                    <td colspan="" class="w-75" style="vertical-align: middle;">
                                        {% if item.url %}
                                            <a href="{{ item.url }}">{{ item.name }}</a>
                                        {% elif itemtype == "Note" %}
                                            <a href="{% url 'note:detail' item.id %}">{{ item.name }}</a>
                                        {% else %}
                                            {{ item.name }}
                                        {% endif %}
                                    {% if item.tags.all %}
                                                <div class="float-right">
                                                    {% for tag in item.tags.all %}
                                                        <a href="?tags={{ tag }}" class="ml-2 badge badge-secondary py-2 px-3">{{ tag }}</a>
                                                    {% endfor %}
                                                </div>
                                            {% endif %}
                                    </td>
                                    {# Item CRUD Buttons #}
                                    <td colspan="" class="d-flex justify-content-around align-items-center text-right" style="">
                                        <a class="btn btn-sm btn-outline-info" style="width: 2rem; height: 2rem;" href="
                                            {% if itemtype == 'Todo' %}
                                            {% url 'todo:detail' item.id %}
                                            {% elif itemtype == 'Note' %}
                                            {% url 'note:detail' item.id %}
                                            {% elif itemtype == 'Bookmark' %}
                                            {% url 'bookmark:detail' item.id %}
                                            {% endif %}"
                                        ><i class="bi bi-eye-fill" style=""></i>
                                        </a>
                                        <a class="btn btn-sm btn-outline-warning" style="width: 2rem; height: 2rem;" href="
                                            {% if itemtype == 'Todo' %}
                                            {% url 'todo:update' item.id %}
                                            {% elif itemtype == 'Note' %}
                                            {% url 'note:update' item.id %}
                                            {% elif itemtype == 'Bookmark' %}
                                            {% url 'bookmark:update' item.id %}
                                            {% endif %}"
                                        ><i class="bi bi-pen-fill"></i>&nbsp;
                                        </a>
                                        <a class="btn btn-sm btn-outline-danger" style="width: 2rem; height: 2rem;" href="#"
                                                {% if itemtype == 'Todo' %}
                                           onclick="if (this.innerHTML==='&Cross;'){this.href='{% url 'todo:delete' item.id %}'};this.innerHTML='&Cross;';"
                                                {% elif itemtype == 'Note' %}
                                           onclick="if (this.innerHTML==='&Cross;'){this.href='{% url 'note:delete' item.id %}'};this.innerHTML='&Cross;';"
                                                {% elif itemtype == 'Bookmark' %}
                                           onclick="if (this.innerHTML==='&Cross;'){this.href='{% url 'bookmark:delete' item.id %}'};this.innerHTML='&Cross;';"
                                                {% endif %}
                                        ><i class="bi bi-trash2-fill"></i>&nbsp;
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="1">
                                        {{ item.description }}
                                    </td>
                                    <td class="text-center border-0">
                                        {% if item.text_content %}
                                            <div class="text-muted">{{ item.text_content  | length }} chars.</div>
                                        {% endif %}
                                        {% if item.due_date %}
                                            <span class="{% if item.due_date %}text-danger {% else %} text-success {% endif %}">Due {{ item.due_date |naturalday}}</span>
                                            {#                                            TODO: Add  logic to determine if date is overdue.#}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endwith %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% include 'paginator.html' %}
            </div>
        </div>
    </div>
    <script>
        document.querySelectorAll('tbody > tr').forEach(x => {
            if (x.children.length > 2) x.classList.add('trborder')
        })
    </script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load get_class %}
{% block content %}
    <div class="row">
        <div class="col-12 mt-2">
            <div class="jumbotron pt-4">
                {% include 'components/sorting_bar.html' %}
                <div class="d-flex flex-wrap justify-content-center mt-4">
                    {% for item in page_obj %}
                        {% with itemtype=item|get_class %}
                            {% if itemtype == 'Todo' %}
                                {% include 'todo/list_card.html' %}
                            {% elif itemtype == 'Note' %}
                                {% include 'note/list_card.html' %}
                            {% elif itemtype == 'Bookmark' %}
                                {% include 'bookmark/list_card.html' %}
                            {% endif %}
                        {% endwith %}
                    {% endfor %}
                </div>
                {% include 'paginator.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded py-1 mb-2">
    <a tabindex="-1" class="navbar-brand" href="#">{{ user }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a tabindex="-1" class="nav-link" href="/">All Items</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Create New
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'todo:create' %}">New Todo</a>
                    <a class="dropdown-item" href="{% url 'note:create' %}">New Note</a>
                    <a class="dropdown-item" href="{% url 'bookmark:create' %}">New Bookmark</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Administer Tags</a>
                </div>
            </li>
            <li class="nav-item">
                <a tabindex="-1" class="nav-link" href="">Archive</a>
                {#                TODO: Implement#}
            </li>
            <li class="nav-item">
                <a tabindex="-1" class="nav-link" href="{% url 'export-user-db' %}">Export Data</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a tabindex="1" class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% elif not request.user.is_authenticated %}
                <li class="nav-item">
                    <a tabindex="1" class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a tabindex="1" class="nav-link" href="{% url 'signup' %}">Signup</a>
                </li>
            {% endif %}
        </ul>
        <div class="ml-auto">
            <form method="post">
                {% csrf_token %}
                <div class="input-group m-0 mb-1">
                    <input tabindex="1" onkeypress="if (event.keyCode === 13){submit();}" class="{% if request.session.search %} bg-warning text-white {% endif %}form-control" name="search" type="search" value="{{ request.session.search }}" placeholder="Search Items 🔍" aria-label="Search" style="">
                    <button tabindex="2" onclick="this.value='true';submit();" class="btn btn-sm btn-info" name="reset" value="" type="submit">Reset</button>
                    <button tabindex="3" class="btn btn-sm btn-success border-0" type="submit">Search</button>
                </div>
            </form>
        </div>
    </div>
</nav>

templates/paginator.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% endif %}

        {% if page_obj.number|add:'-4' > 1 %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
              </span>
                </li>
            {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>